version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet publish -c Release --output ./published
      - run: ssh -y circle@178.62.60.163 -y rm -rf /app
      - run: scp -r ./published $USER_ID@178.62.60.163:/home/circle/app 
      - run: ssh circle@178.62.60.163 sudo systemctl restart dotnet-core-app.service
      - store_artifacts:
          path: /temp/bin/Debug/netcoreapp2.0/Courses_app.dll